name: luad-met
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - requests
  - pyyaml
  - jupyter
  - pip
  - pip:
      - torch
      - iterative-stratification